"""creation table offres

Revision ID: 0cca8a7d98a4
Revises: 
Create Date: 2026-07-20 01:48:36.286363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cca8a7d98a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('competences_requises', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'soumise', 'publiee', 'refusee', name='statut_offre_enum'), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offres')
    # ### end Alembic commands ###
